"""
Tests for backend/pipeline/video.py

All tests operate on the synthetic test video generated by fixtures.
Run after generating fixtures::

    python tests/fixtures/generate_test_fixtures.py
    pytest tests/test_video.py -v
"""

from __future__ import annotations

import os
import shutil
import tempfile
from pathlib import Path

import pytest

from tests.fixtures.generate_test_fixtures import (
    TEST_VIDEO_PATH,
    generate_silent_wav,
    generate_test_video,
)


# ---------------------------------------------------------------------------
# Fixture: ensure test video exists
# ---------------------------------------------------------------------------


@pytest.fixture(scope="module", autouse=True)
def ensure_test_video():
    """Generate the synthetic test video if it does not already exist."""
    if not TEST_VIDEO_PATH.exists():
        generate_test_video()
    yield


@pytest.fixture
def tmp_session(tmp_path):
    """Provide a temporary session directory that mimics data/sessions/<id>."""
    sess = tmp_path / "test_session"
    sess.mkdir()
    return sess


# ---------------------------------------------------------------------------
# Tests
# ---------------------------------------------------------------------------


class TestSaveVideo:
    def test_save_bytes(self, tmp_path, monkeypatch):
        """save_video() should write bytes to disk and return valid metadata."""
        from backend.pipeline.video import save_video
        import backend.pipeline.video as video_module

        # Redirect SESSIONS_DIR to tmp_path
        monkeypatch.setattr(video_module, "SESSIONS_DIR", tmp_path)

        video_bytes = TEST_VIDEO_PATH.read_bytes()
        meta = save_video(video_bytes, filename="test.mp4", session_id="unit-test-save")

        assert Path(meta.file_path).exists()
        assert meta.session_id == "unit-test-save"
        assert meta.duration_seconds > 0
        assert meta.fps > 0
        assert meta.width == 640
        assert meta.height == 360
        assert meta.total_frames > 0

    def test_save_file(self, tmp_path, monkeypatch):
        """save_video_file() should copy an existing file and return metadata."""
        from backend.pipeline.video import save_video_file
        import backend.pipeline.video as video_module

        monkeypatch.setattr(video_module, "SESSIONS_DIR", tmp_path)

        meta = save_video_file(str(TEST_VIDEO_PATH), session_id="unit-test-copy")

        assert Path(meta.file_path).exists()
        assert meta.width == 640
        assert meta.height == 360


class TestExtractFrames:
    def test_extraction_count(self, tmp_path, monkeypatch):
        """extract_frames at 1 fps should produce ~10 frames for a 10s video."""
        from backend.pipeline.video import extract_frames, save_video_file
        import backend.pipeline.video as video_module

        monkeypatch.setattr(video_module, "SESSIONS_DIR", tmp_path)

        meta = save_video_file(str(TEST_VIDEO_PATH), session_id="extract-test")
        frames = extract_frames(meta, fps=1.0, output_dir=str(tmp_path / "frames"))

        # 10 second video @ 1 fps -> ~10 frames (allow ±1 for rounding)
        assert 9 <= len(frames) <= 11

    def test_frames_are_sorted_by_timestamp(self, tmp_path, monkeypatch):
        from backend.pipeline.video import extract_frames, save_video_file
        import backend.pipeline.video as video_module

        monkeypatch.setattr(video_module, "SESSIONS_DIR", tmp_path)

        meta = save_video_file(str(TEST_VIDEO_PATH), session_id="sort-test")
        frames = extract_frames(meta, fps=1.0, output_dir=str(tmp_path / "frames"))

        timestamps = [f.timestamp for f in frames]
        assert timestamps == sorted(timestamps)

    def test_frame_files_exist(self, tmp_path, monkeypatch):
        from backend.pipeline.video import extract_frames, save_video_file
        import backend.pipeline.video as video_module

        monkeypatch.setattr(video_module, "SESSIONS_DIR", tmp_path)

        meta = save_video_file(str(TEST_VIDEO_PATH), session_id="files-test")
        frames_dir = tmp_path / "frames"
        frames = extract_frames(meta, fps=1.0, output_dir=str(frames_dir))

        for f in frames:
            assert Path(f.file_path).exists(), f"Frame file missing: {f.file_path}"

    def test_higher_fps_yields_more_frames(self, tmp_path, monkeypatch):
        from backend.pipeline.video import extract_frames, save_video_file
        import backend.pipeline.video as video_module

        monkeypatch.setattr(video_module, "SESSIONS_DIR", tmp_path)

        meta = save_video_file(str(TEST_VIDEO_PATH), session_id="fps-test")
        frames_1fps = extract_frames(meta, fps=1.0, output_dir=str(tmp_path / "frames_1"))
        frames_2fps = extract_frames(meta, fps=2.0, output_dir=str(tmp_path / "frames_2"))

        assert len(frames_2fps) > len(frames_1fps)


class TestKeyframeDetection:
    def test_first_frame_is_keyframe(self, tmp_path, monkeypatch):
        from backend.pipeline.video import detect_keyframes, extract_frames, save_video_file
        import backend.pipeline.video as video_module

        monkeypatch.setattr(video_module, "SESSIONS_DIR", tmp_path)

        meta = save_video_file(str(TEST_VIDEO_PATH), session_id="kf-test")
        frames = extract_frames(meta, fps=1.0, output_dir=str(tmp_path / "frames"))
        frames = detect_keyframes(frames)

        assert frames[0].is_keyframe is True

    def test_scene_change_scores_populated(self, tmp_path, monkeypatch):
        from backend.pipeline.video import detect_keyframes, extract_frames, save_video_file
        import backend.pipeline.video as video_module

        monkeypatch.setattr(video_module, "SESSIONS_DIR", tmp_path)

        meta = save_video_file(str(TEST_VIDEO_PATH), session_id="kf-scores-test")
        frames = extract_frames(meta, fps=1.0, output_dir=str(tmp_path / "frames"))
        frames = detect_keyframes(frames)

        # Every frame should have a scene change score
        for f in frames:
            assert f.scene_change_score is not None

    def test_slide_transitions_detected(self, tmp_path, monkeypatch):
        """The synthetic video has 5 colour changes — expect at least 2 keyframes."""
        from backend.pipeline.video import detect_keyframes, extract_frames, save_video_file
        import backend.pipeline.video as video_module

        monkeypatch.setattr(video_module, "SESSIONS_DIR", tmp_path)

        meta = save_video_file(str(TEST_VIDEO_PATH), session_id="kf-slide-test")
        # 2 fps to catch all slide transitions
        frames = extract_frames(meta, fps=2.0, output_dir=str(tmp_path / "frames"))
        frames = detect_keyframes(frames, threshold=0.1)

        keyframe_count = sum(1 for f in frames if f.is_keyframe)
        assert keyframe_count >= 2


class TestExtractAudio:
    def test_audio_extracted_from_real_video(self, tmp_path, monkeypatch):
        """extract_audio raises RuntimeError when the video has no audio stream."""
        if shutil.which("ffmpeg") is None:
            pytest.skip("ffmpeg not installed")

        from backend.pipeline.video import extract_audio, save_video_file
        import backend.pipeline.video as video_module

        monkeypatch.setattr(video_module, "SESSIONS_DIR", tmp_path)

        # The synthetic test video is video-only (no audio stream) —
        # extract_audio should raise RuntimeError with a clear message
        meta = save_video_file(str(TEST_VIDEO_PATH), session_id="audio-test")
        with pytest.raises(RuntimeError):
            extract_audio(meta, output_dir=str(tmp_path / "audio"))

    def test_audio_raises_without_ffmpeg(self, tmp_path, monkeypatch):
        """extract_audio should raise RuntimeError when ffmpeg is missing."""
        from backend.pipeline import video as video_module
        from backend.pipeline.video import extract_audio, save_video_file

        monkeypatch.setattr(video_module, "SESSIONS_DIR", tmp_path)
        monkeypatch.setattr("shutil.which", lambda _: None)

        meta = save_video_file(str(TEST_VIDEO_PATH), session_id="no-ffmpeg-test")

        with pytest.raises(RuntimeError, match="ffmpeg"):
            extract_audio(meta, output_dir=str(tmp_path / "audio"))
